name: fundingrate
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.1.0
  teledart: ^0.6.1
  dotenv: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.0.17
  build_runner: ^2.1.2
  intl_utils: ^2.8.13

intl_utils:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
