name: fundingrate
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.1.0
  dio: ^5.4.3+1
  teledart: ^0.6.1
  dotenv: ^4.0.0
  intl: ^0.20.2
  get_it: ^9.2.0
  logger: ^2.6.2
  equatable: ^2.0.8
  dartz: ^0.10.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.0.17
  build_runner: ^2.1.2
  intl_utils: ^2.8.13

intl_utils:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
